title: Sohobase
email: hi@sohobase.com
url:   "http://sohobase.co"
description: >
  A decentralized studio, creating Crypto stuff.

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
  style: :compressed

gems:
  - jekyll-sitemap
