
# SEO settings
title: sinbase
title2: "" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://sohobase.co # site url
baseurl: null

google_analytics: UA-XXXXX-XX
repo: http://github.com/sohobase/site
disqus_shortname: "soyjavi"
twitter_username: "soyjavi"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
# destination: ./_site

# Sass configuration
sass:
  # sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Javi Jimenez"
  job      : "R&D Software Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : hello@soyjavi.com
  url      : http://soyjavi.com
  github   : http://github.com/soyjavi
  twitter  : http://twitter.com/soyjavi
  linkedin : http://linkedin.com/in/javi.jimenez.villar

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@soyjavi"

# gems:
#   - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["node_modules", "src", "Gemfile", "Gemfile.lock", "package.json", "README.md"]
